---
abstract: 'LIMS2 REST Client'
author:
  - 'Ray Miller <rm7@sanger.ac.uk>'
build_requires:
  Const::Fast: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Test::More: 0.88
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LIMS2-REST-Client
requires:
  Data::Dump: 0
  Getopt::Long: 0
  HTTP::Request: 0
  HTTP::Status: 0
  JSON: 0
  LWP::UserAgent: 0
  Log::Log4perl: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Log::Log4perl: 0
  MooseX::MarkAsMethods: 0
  MooseX::SimpleConfig: 0
  MooseX::Types::URI: 0
  Scalar::Util: 0
  Throwable: 0
  Try::Tiny: 0
  URI: 0
  namespace::autoclean: 0
  overload: 0
  strict: 0
  warnings: 0
version: 0.002
